---
# tasks file for python-setup-pyenv-pipx-poetry

- name: confirm that user exists or create
  ansible.builtin.user:
    name: '{{ user }}'
  register: user_registered
  check_mode: true

- name: Check if pyenv exists
  ansible.builtin.stat:
    path: '{{ user_registered.home }}/.pyenv'
  register: pyenv_exists

- name: Install pyenv requirements debian/like
  when: pyenv_exists.stat.exists == False and ansible_pkg_mgr == "apt"
  apt: 
    state: present
    name: git,make,build-essential,libssl-dev,zlib1g-dev,libbz2-dev,libreadline-dev,libsqlite3-dev,wget,curl,llvm,libncursesw5-dev,xz-utils,tk-dev,libxml2-dev,libxmlsec1-dev,libffi-dev,liblzma-dev,python3-dev,python3-venv,python3-pip

- name: Install pyenv requirements arch
  when: pyenv_exists.stat.exists == False and ansible_pkg_mgr == "pacman"
  community.general.pacman:
    state: present
    name:
      - base-devel
      - openssl
      - zlib
      - xz
      - tk
      - python-pip
      - python-setuptools

- name: Install pyenv linux
  become_user: '{{ user }}'
  shell: curl https://pyenv.run | bash
  when: pyenv_exists.stat.exists == False and ansible_os_family != "Darwin"

- name: Install pyenv macos
  become: true
  become_user: '{{ user }}'
  community.general.homebrew:
    name: pyenv
    state: present
  when: pyenv_exists.stat.exists == False and ansible_os_family == "Darwin"

- name: check is pipx installed
  become_user: '{{ user }}'
  shell: command -v pipx
  register: pipx_exists
  ignore_errors: true

- name: pipx linux
  when: pipx_exists is failed
  ansible.builtin.pip:
    name: pipx

- name: check is poetry installed
  become_user: '{{ user }}'
  shell: command -v poetry
  register: poetry_exists
  ignore_errors: true

- name: Install poetry on pipx
  when: poetry_exists is failed
  become_user: '{{ user }}'
  community.general.pipx:
    name: poetry

- name: check is commitizen installed
  become_user: '{{ user }}'
  shell: command -v cz
  register: commitizen_exists
  ignore_errors: true

- name: Install commitizen
  when: commitizen_exists is failed
  become_user: '{{ user }}'
  community.general.pipx:
    name: commitizen

- name: inject emoji into pipx commitizen
  when: commitizen_exists is failed
  become_user: '{{ user }}'
  community.general.pipx:
    name: commitizen
    state: inject
    inject_packages:
      - commitizen-emoji
